WINDOW_WIDTH = 600
WINDOW_HEIGHT = 900

BUTTON_SIZE_W = 200
BUTTON_SIZE_H = 100

TEXTBOX_W = WINDOW_WIDTH - 20
TEXTBOX_H =  WINDOW_HEIGHT / 2

#######BUTTON 1#########
BUTTON_1_POSITION_X = 30
BUTTON_1_POSITION_Y = (WINDOW_HEIGHT/2 + 100)


#######BUTTON 2#########
BUTTON_2_POSITION_X = WINDOW_WIDTH - (30 + BUTTON_SIZE_W)
BUTTON_2_POSITION_Y = (WINDOW_HEIGHT/2 + 100)


#######BUTTON 3#########
BUTTON_3_POSITION_X = 30
BUTTON_3_POSITION_Y = WINDOW_HEIGHT - (BUTTON_SIZE_H) - 20


#######BUTTON 4#########
BUTTON_4_POSITION_X = WINDOW_WIDTH - (30 + BUTTON_SIZE_W)
BUTTON_4_POSITION_Y = WINDOW_HEIGHT - (BUTTON_SIZE_H) - 20